import 'dart:convert';
import '../services/icon_fetch_strategy.dart';

class AppGroup {
  String name;
  List<String> items;
  bool isAutoGenerated;
  bool collapsed;

  AppGroup({
    required this.name,
    this.items = const [],
    this.isAutoGenerated = false,
    this.collapsed = false,
  });

  factory AppGroup.fromJson(Map<String, dynamic> json) => AppGroup(
        name: json['name'] as String,
        items: (json['items'] as List<dynamic>?)?.cast<String>() ?? [],
        isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
        collapsed: json['collapsed'] as bool? ?? false,
      );

  Map<String, dynamic> toJson() => {
        'name': name,
        'items': items,
        'isAutoGenerated': isAutoGenerated,
        'collapsed': collapsed,
      };
}

class AppDrawerSettings {
  String appLaunchCommand;
  IconFetchMethod iconFetchMethod;
  List<String> favorites;
  List<AppGroup> groups;
  bool autoGroupByCategory;
  bool showScripts;
  bool otherCollapsed;
  bool scriptsCollapsed;

  static const String _defaultCommand =
      'scrcpy --pause-on-exit=if-error --new-display=1920x1080';

  AppDrawerSettings({
    this.appLaunchCommand = _defaultCommand,
    this.iconFetchMethod = IconFetchMethod.adbScrape,
    List<String>? favorites,
    List<AppGroup>? groups,
    this.autoGroupByCategory = true,
    this.showScripts = false,
    this.otherCollapsed = false,
    this.scriptsCollapsed = false,
  })  : favorites = favorites ?? [],
        groups = groups ?? [];

  factory AppDrawerSettings.fromJson(Map<String, dynamic> json) =>
      AppDrawerSettings(
        appLaunchCommand:
            json['appLaunchCommand'] as String? ?? _defaultCommand,
        iconFetchMethod:
            iconFetchMethodFromString(json['iconFetchMethod'] as String?),
        favorites:
            (json['favorites'] as List<dynamic>?)?.cast<String>() ?? [],
        groups: (json['groups'] as List<dynamic>?)
                ?.map((e) => AppGroup.fromJson(e as Map<String, dynamic>))
                .toList() ??
            [],
        autoGroupByCategory:
            json['autoGroupByCategory'] as bool? ?? true,
        showScripts: json['showScripts'] as bool? ?? false,
        otherCollapsed: json['otherCollapsed'] as bool? ?? false,
        scriptsCollapsed: json['scriptsCollapsed'] as bool? ?? false,
      );

  Map<String, dynamic> toJson() => {
        'appLaunchCommand': appLaunchCommand,
        'iconFetchMethod': iconFetchMethod.name,
        'favorites': favorites,
        'groups': groups.map((g) => g.toJson()).toList(),
        'autoGroupByCategory': autoGroupByCategory,
        'showScripts': showScripts,
        'otherCollapsed': otherCollapsed,
        'scriptsCollapsed': scriptsCollapsed,
      };

  String toJsonString() => jsonEncode(toJson());

  factory AppDrawerSettings.fromJsonString(String jsonString) =>
      AppDrawerSettings.fromJson(jsonDecode(jsonString));
}
