import 'dart:convert';
import '../services/icon_fetch_strategy.dart';

/// A user-defined or auto-generated grouping of apps. Immutable — use
/// [copyWith] to derive a new instance.
class AppGroup {
  final String name;
  final List<String> items;
  final bool isAutoGenerated;
  final bool collapsed;

  AppGroup({
    required this.name,
    List<String> items = const [],
    this.isAutoGenerated = false,
    this.collapsed = false,
  }) : items = List.unmodifiable(items);

  AppGroup copyWith({
    String? name,
    List<String>? items,
    bool? isAutoGenerated,
    bool? collapsed,
  }) =>
      AppGroup(
        name: name ?? this.name,
        items: items ?? this.items,
        isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
        collapsed: collapsed ?? this.collapsed,
      );

  factory AppGroup.fromJson(Map<String, dynamic> json) => AppGroup(
        name: json['name'] as String,
        items: (json['items'] as List<dynamic>?)?.cast<String>() ?? const [],
        isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
        collapsed: json['collapsed'] as bool? ?? false,
      );

  Map<String, dynamic> toJson() => {
        'name': name,
        'items': items,
        'isAutoGenerated': isAutoGenerated,
        'collapsed': collapsed,
      };
}

/// App Drawer settings. Immutable — use [copyWith] to derive a new instance.
class AppDrawerSettings {
  final String appLaunchCommand;
  final IconFetchMethod iconFetchMethod;
  final List<String> favorites;
  final List<AppGroup> groups;
  final bool autoGroupByCategory;
  final bool showScripts;
  final bool otherCollapsed;
  final bool scriptsCollapsed;
  final bool includeSystemApps;

  static const String _defaultCommand =
      'scrcpy --pause-on-exit=if-error --new-display=1920x1080';

  AppDrawerSettings({
    this.appLaunchCommand = _defaultCommand,
    this.iconFetchMethod = IconFetchMethod.adbScrape,
    List<String>? favorites,
    List<AppGroup>? groups,
    this.autoGroupByCategory = true,
    this.showScripts = false,
    this.otherCollapsed = false,
    this.scriptsCollapsed = false,
    this.includeSystemApps = false,
  })  : favorites = List.unmodifiable(favorites ?? const []),
        groups = List.unmodifiable(groups ?? const []);

  AppDrawerSettings copyWith({
    String? appLaunchCommand,
    IconFetchMethod? iconFetchMethod,
    List<String>? favorites,
    List<AppGroup>? groups,
    bool? autoGroupByCategory,
    bool? showScripts,
    bool? otherCollapsed,
    bool? scriptsCollapsed,
    bool? includeSystemApps,
  }) =>
      AppDrawerSettings(
        appLaunchCommand: appLaunchCommand ?? this.appLaunchCommand,
        iconFetchMethod: iconFetchMethod ?? this.iconFetchMethod,
        favorites: favorites ?? this.favorites,
        groups: groups ?? this.groups,
        autoGroupByCategory: autoGroupByCategory ?? this.autoGroupByCategory,
        showScripts: showScripts ?? this.showScripts,
        otherCollapsed: otherCollapsed ?? this.otherCollapsed,
        scriptsCollapsed: scriptsCollapsed ?? this.scriptsCollapsed,
        includeSystemApps: includeSystemApps ?? this.includeSystemApps,
      );

  factory AppDrawerSettings.fromJson(Map<String, dynamic> json) =>
      AppDrawerSettings(
        appLaunchCommand:
            json['appLaunchCommand'] as String? ?? _defaultCommand,
        iconFetchMethod:
            iconFetchMethodFromString(json['iconFetchMethod'] as String?),
        favorites:
            (json['favorites'] as List<dynamic>?)?.cast<String>() ?? const [],
        groups: (json['groups'] as List<dynamic>?)
                ?.map((e) => AppGroup.fromJson(e as Map<String, dynamic>))
                .toList() ??
            const [],
        autoGroupByCategory:
            json['autoGroupByCategory'] as bool? ?? true,
        showScripts: json['showScripts'] as bool? ?? false,
        otherCollapsed: json['otherCollapsed'] as bool? ?? false,
        scriptsCollapsed: json['scriptsCollapsed'] as bool? ?? false,
        includeSystemApps: json['includeSystemApps'] as bool? ?? false,
      );

  Map<String, dynamic> toJson() => {
        'appLaunchCommand': appLaunchCommand,
        'iconFetchMethod': iconFetchMethod.name,
        'favorites': favorites,
        'groups': groups.map((g) => g.toJson()).toList(),
        'autoGroupByCategory': autoGroupByCategory,
        'showScripts': showScripts,
        'otherCollapsed': otherCollapsed,
        'scriptsCollapsed': scriptsCollapsed,
        'includeSystemApps': includeSystemApps,
      };

  String toJsonString() => jsonEncode(toJson());

  factory AppDrawerSettings.fromJsonString(String jsonString) =>
      AppDrawerSettings.fromJson(jsonDecode(jsonString));
}
