/// Common Android Package Names to Display Labels Mapping
///
/// A curated dictionary of popular Android applications for instant name resolution
/// without requiring ADB queries. This list covers the most widely used apps across
/// various categories including social media, productivity, gaming, entertainment, etc.
///
/// Usage: Used by TerminalService.getPackageLabel() for fast app name lookup
library;

const Map<String, String> commonPackageNames = {
  // Google Apps
  'com.android.chrome': 'Chrome',
  'com.chrome.beta': 'Chrome Beta',
  'com.chrome.dev': 'Chrome Dev',
  'com.chrome.canary': 'Chrome Canary',
  'com.google.android.youtube': 'YouTube',
  'com.google.android.apps.youtube.music': 'YouTube Music',
  'com.google.android.apps.youtube.creator': 'YouTube Studio',
  'com.google.android.apps.youtube.kids': 'YouTube Kids',
  'com.google.android.gm': 'Gmail',
  'com.google.android.apps.maps': 'Google Maps',
  'com.google.android.apps.docs': 'Google Docs',
  'com.google.android.apps.docs.editors.sheets': 'Google Sheets',
  'com.google.android.apps.docs.editors.slides': 'Google Slides',
  'com.google.android.apps.docs.editors.docs': 'Google Docs Editor',
  'com.google.android.apps.photos': 'Google Photos',
  'com.google.android.apps.messaging': 'Messages',
  'com.google.android.contacts': 'Contacts',
  'com.google.android.calendar': 'Calendar',
  'com.google.android.googlequicksearchbox': 'Google',
  'com.google.android.apps.fitness': 'Google Fit',
  'com.google.android.apps.translate': 'Google Translate',
  'com.google.android.keep': 'Google Keep',
  'com.google.android.apps.podcasts': 'Google Podcasts',
  'com.google.android.play.games': 'Google Play Games',
  'com.google.android.apps.wallpaper': 'Wallpapers',
  'com.google.android.gms': 'Google Play Services',
  'com.google.android.apps.tachyon': 'Google Meet',
  'com.google.android.talk': 'Google Hangouts',
  'com.google.android.apps.authenticator2': 'Google Authenticator',
  'com.google.android.apps.wellbeing': 'Digital Wellbeing',
  'com.google.android.apps.magazines': 'Google News',
  'com.google.android.apps.books': 'Google Play Books',
  'com.google.android.videos': 'Google TV',
  'com.google.android.music': 'Google Play Music',
  'com.google.android.apps.turbo': 'Datally',
  'com.google.android.apps.nbu.files': 'Files by Google',
  'com.google.android.inputmethod.latin': 'Gboard',
  'com.google.ar.lens': 'Google Lens',
  'com.google.android.apps.recorder': 'Recorder',
  'com.android.vending': 'Google Play Store',

  // Social Media
  'com.facebook.katana': 'Facebook',
  'com.facebook.lite': 'Facebook Lite',
  'com.facebook.orca': 'Messenger',
  'com.facebook.mlite': 'Messenger Lite',
  'com.instagram.android': 'Instagram',
  'com.instagram.lite': 'Instagram Lite',
  'com.whatsapp': 'WhatsApp',
  'com.whatsapp.w4b': 'WhatsApp Business',
  'com.twitter.android': 'Twitter',
  'com.twitter.android.lite': 'Twitter Lite',
  'com.zhiliaoapp.musically': 'TikTok',
  'com.ss.android.ugc.trill': 'TikTok',
  'com.snapchat.android': 'Snapchat',
  'com.linkedin.android': 'LinkedIn',
  'com.reddit.frontpage': 'Reddit',
  'com.pinterest': 'Pinterest',
  'com.tumblr': 'Tumblr',
  'com.discord': 'Discord',
  'com.Slack': 'Slack',
  'org.telegram.messenger': 'Telegram',
  'org.telegram.messenger.web': 'Telegram X',
  'com.viber.voip': 'Viber',
  'jp.naver.line.android': 'LINE',
  'com.vkontakte.android': 'VK',
  'com.sina.weibo': 'Weibo',
  'com.tencent.mm': 'WeChat',
  'com.tencent.mobileqq': 'QQ',
  'com.imo.android.imoim': 'imo',
  'com.kakao.talk': 'KakaoTalk',
  'com.facebook.pages.app': 'Meta Business Suite',

  // Entertainment & Streaming
  'com.netflix.mediaclient': 'Netflix',
  'com.amazon.avod.thirdpartyclient': 'Prime Video',
  'com.hulu.plus': 'Hulu',
  'com.disney.disneyplus': 'Disney+',
  'com.hbo.hbonow': 'HBO Max',
  'com.wbd.stream': 'Max',
  'com.showtime.standalone': 'Showtime',
  'com.cbs.app': 'Paramount+',
  'com.apple.android.music': 'Apple Music',
  'com.spotify.music': 'Spotify',
  'com.spotify.lite': 'Spotify Lite',
  'com.amazon.mp3': 'Amazon Music',
  'deezer.android.app': 'Deezer',
  'com.pandora.android': 'Pandora',
  'com.soundcloud.android': 'SoundCloud',
  'tv.twitch.android.app': 'Twitch',
  'com.tidal': 'Tidal',
  'fm.last.android': 'Last.fm',
  'com.aspiro.tidal': 'Tidal',
  'com.vevo': 'Vevo',
  'com.plexapp.android': 'Plex',
  'com.mxtech.videoplayer.ad': 'MX Player',
  'com.mxtech.videoplayer.pro': 'MX Player Pro',
  'org.videolan.vlc': 'VLC',
  'com.bambuna.podcastaddict': 'Podcast Addict',

  // Shopping
  'com.amazon.mShop.android.shopping': 'Amazon Shopping',
  'com.amazon.mShop.android': 'Amazon',
  'com.ebay.mobile': 'eBay',
  'com.shopify.mobile': 'Shopify',
  'com.etsy.android': 'Etsy',
  'com.alibaba.aliexpresshd': 'AliExpress',
  'com.contextlogic.wish': 'Wish',
  'com.walmart.android': 'Walmart',
  'com.target.ui': 'Target',
  'com.bestbuy.android': 'Best Buy',
  'com.zara.android': 'Zara',
  'com.nike.omega': 'Nike',
  'com.adidas.app': 'Adidas',
  'com.sephora.mobileapp': 'Sephora',
  'com.ikea.mobile.android': 'IKEA',

  // Productivity
  'com.microsoft.office.outlook': 'Outlook',
  'com.microsoft.office.word': 'Microsoft Word',
  'com.microsoft.office.excel': 'Microsoft Excel',
  'com.microsoft.office.powerpoint': 'PowerPoint',
  'com.microsoft.teams': 'Microsoft Teams',
  'com.microsoft.office.officehubrow': 'Microsoft 365',
  'com.microsoft.office.onenote': 'OneNote',
  'com.dropbox.android': 'Dropbox',
  'com.evernote': 'Evernote',
  'com.todoist': 'Todoist',
  'com.notion.id': 'Notion',
  'com.trello': 'Trello',
  'com.asana.app': 'Asana',
  'com.readdle.spark': 'Spark Mail',
  'com.simplemobiletools.calendar': 'Simple Calendar',
  'com.simplemobiletools.notes': 'Simple Notes',
  'com.anydo': 'Any.do',
  'com.ticktick.task': 'TickTick',
  'com.habitrpg.android.habitica': 'Habitica',
  'com.box.android': 'Box',
  'com.contextlogic.geek': 'Geek',

  // Gaming - Battle Royale & Shooters
  'com.roblox.client': 'Roblox',
  'com.pubg.imobile': 'PUBG Mobile',
  'com.pubg.krmobile': 'PUBG Mobile KR',
  'com.tencent.ig': 'PUBG Mobile',
  'com.rekoo.pubgm': 'PUBG Mobile',
  'com.epicgames.fortnite': 'Fortnite',
  'com.activision.callofduty.shooter': 'Call of Duty Mobile',
  'com.garena.game.codm': 'Call of Duty Mobile',
  'com.activision.callofduty.warzone': 'Call of Duty Warzone',
  'com.ea.gp.apexlegendsmobilefps': 'Apex Legends Mobile',
  'com.dts.freefireth': 'Free Fire',
  'com.dts.freefiremax': 'Free Fire Max',
  'com.tencent.tmgp.kr.codm': 'Call of Duty Mobile KR',

  // Gaming - Supercell Games
  'com.supercell.clashofclans': 'Clash of Clans',
  'com.supercell.clashroyale': 'Clash Royale',
  'com.supercell.brawlstars': 'Brawl Stars',
  'com.supercell.hayday': 'Hay Day',
  'com.supercell.boombeach': 'Boom Beach',
  'com.supercell.squadbusters': 'Squad Busters',

  // Gaming - Sandbox & Creative
  'com.mojang.minecraftpe': 'Minecraft',
  'com.mojang.minecraftearth': 'Minecraft Earth',
  'com.wb.goog.legobatmanbeyondgotham': 'LEGO Batman',
  'com.telltalegames.minecraft100': 'Minecraft Story Mode',
  'com.innersloth.spacemafia': 'Among Us',
  'com.axlebolt.standoff2': 'Standoff 2',

  // Gaming - Racing
  'com.gameloft.android.ANMP.GloftA8HM': 'Asphalt 8',
  'com.gameloft.android.ANMP.GloftA9HM': 'Asphalt 9',
  'com.ea.games.r3_row': 'Real Racing 3',
  'com.naturalmotion.customstreetracer2': 'CSR Racing 2',
  'com.ea.game.nfs14_row': 'Need for Speed',
  'com.ea.games.nfs13_na': 'Need for Speed Most Wanted',
  'com.wb.goog.mkx': 'Mortal Kombat X',
  'com.miniclip.racingrivals': 'Racing Rivals',
  'com.hutchgames.rebelracing': 'Rebel Racing',
  'com.fingersoft.hillclimb': 'Hill Climb Racing',
  'com.fingersoft.hillclimb2': 'Hill Climb Racing 2',

  // Gaming - MOBA & Strategy
  'com.mobile.legends': 'Mobile Legends',
  'com.garena.game.kgvn': 'Arena of Valor',
  'com.tencent.tmgp.sgame': 'Honor of Kings',
  'com.vainglory': 'Vainglory',
  'com.superevilmegacorp.game': 'Vainglory',
  'com.riotgames.league.wildrift': 'League of Legends Wild Rift',
  'com.riotgames.league.teamfighttactics': 'Teamfight Tactics',
  'com.im30.ROE.PlayStore': 'Ring of Elysium',

  // Gaming - RPG & Adventure
  'com.miHoYo.GenshinImpact': 'Genshin Impact',
  'com.miHoYo.Yuanshen': 'Genshin Impact CN',
  'com.miHoYo.hkrpg': 'Honkai Star Rail',
  'com.miHoYo.bh3oversea': 'Honkai Impact 3rd',
  'com.YoStarEN.Arknights': 'Arknights',
  'com.YoStarJP.AzurLane': 'Azur Lane',
  'com.netease.eve.en': 'Eve Echoes',
  'com.pearlabyss.blackdesertm.gl': 'Black Desert Mobile',
  'com.nexon.maplem.global': 'MapleStory M',
  'com.netmarble.sololv': 'Solo Leveling Arise',
  'com.square_enix.android_googleplay.FFVIIIFS': 'Final Fantasy VII',
  'com.netease.idv.googleplay': 'Identity V',
  'com.lilithgame.roc.gp': 'Rise of Kingdoms',
  'com.igg.android.lordsmobile': 'Lords Mobile',
  'com.scopely.monopolygo': 'Monopoly GO',
  'com.riotgames.legendsofruneterra': 'Legends of Runeterra',

  // Gaming - Sports
  'com.ea.gp.fifamobile': 'FIFA Mobile',
  'com.ea.gp.easportsufc': 'EA Sports UFC',
  'com.ea.gp.nbamobile': 'NBA Live Mobile',
  'com.konami.pesam': 'eFootball PES',
  'com.firsttouchgames.dls7': 'Dream League Soccer',
  'com.tencent.tmgp.sgame.nba2k': 'NBA 2K',
  'com.ea.gp.madden16': 'Madden NFL',

  // Gaming - Casual & Puzzle
  'com.kiloo.subwaysurf': 'Subway Surfers',
  'com.king.candycrushsaga': 'Candy Crush Saga',
  'com.king.candycrushsodasaga': 'Candy Crush Soda Saga',
  'com.king.candycrush4': 'Candy Crush Friends',
  'com.king.farmheroessaga': 'Farm Heroes Saga',
  'com.rovio.angrybirds': 'Angry Birds',
  'com.rovio.angrybirds2': 'Angry Birds 2',
  'com.rovio.baba': 'Angry Birds Dream Blast',
  'com.halfbrick.fruitninja': 'Fruit Ninja',
  'com.halfbrick.jetpackjoyride': 'Jetpack Joyride',
  'com.plantsvszombies2': 'Plants vs Zombies 2',
  'com.popcap.pvz2': 'Plants vs Zombies 2',
  'com.miniclip.eightballpool': '8 Ball Pool',
  'com.playdemic.golf.android': 'Golf Clash',
  'com.scopely.scrabble': 'Scrabble GO',
  'com.zynga.words3': 'Words With Friends 2',
  'com.nianticlabs.pokemongo': 'Pokémon GO',
  'com.nianticlabs.pikmin': 'Pikmin Bloom',
  'com.thatgamecompany.sky': 'Sky: Children of the Light',
  'com.ustwo.monumentvalley': 'Monument Valley',
  'com.ustwo.monumentvalley2': 'Monument Valley 2',

  // Gaming - Card & Board Games
  'com.blizzard.wtcg.hearthstone': 'Hearthstone',
  'com.CamelotGames.YuGiOhDuelLinks': 'Yu-Gi-Oh! Duel Links',
  'jp.konami.yugioh.duel': 'Yu-Gi-Oh! Master Duel',
  'com.wb.goog.mkx.brawlhalla': 'Brawlhalla',
  'air.com.hypah.io.slither': 'Slither.io',
  'com.voodoo.paper.io': 'Paper.io',
  'com.voodoo.fallingballs': 'Falling Balls',

  // Gaming - Gacha & Anime
  'com.YoStarEN.AzurLane': 'Azur Lane',
  'com.sunborn.girlsfrontline.en': 'Girls Frontline',
  'jp.gungho.padEN': 'Puzzle & Dragons',
  'com.bandainamcoent.dbzdokkanww': 'Dragon Ball Z Dokkan Battle',
  'com.bandainamcoent.dblegends_ww': 'Dragon Ball Legends',
  'com.YoStarJP.BlueArchive': 'Blue Archive',
  'com.nexon.counterside': 'Counter:Side',
  'com.eversoul.global': 'Eversoul',
  'com.nextfloor.Nikke': 'Goddess of Victory: NIKKE',
  'com.ngelgames.sla': 'Saint Seiya Awakening',

  // Emulators - RetroArch & Cores
  'com.retroarch': 'RetroArch',
  'com.retroarch.ra32': 'RetroArch 32-bit',
  'com.retroarch.aarch64': 'RetroArch 64-bit',

  // Emulators - Standalone
  'org.ppsspp.ppsspp': 'PPSSPP',
  'org.ppsspp.ppssppgold': 'PPSSPP Gold',
  'org.dolphinemu.dolphinemu': 'Dolphin Emulator',
  'org.citra.citra_emu': 'Citra 3DS Emulator',
  'org.citra.citra_emu.canary': 'Citra Canary',
  'org.yuzu.yuzu_emu': 'Yuzu',
  'org.skyline.emu': 'Skyline Emulator',
  'xyz.aethersx2.android': 'AetherSX2',
  'com.epsxe.ePSXe': 'ePSXe',
  'com.fpse': 'FPse',
  'com.swordfish.lemuroid': 'Lemuroid',
  'com.drastic.ds': 'DraStic DS Emulator',
  'com.nostalgiaemulators.nesemu': 'Nostalgia.NES',
  'com.nostalgiaemulators.gbaemu': 'Nostalgia.GBA',
  'com.johnemulators.johngba': 'John GBA',
  'com.johnemulators.johngbac': 'John GBA Lite',
  'com.fastemulator.gbafree': 'My Boy! Free',
  'com.fastemulator.gba': 'My Boy!',
  'com.fastemulator.gbc': 'My OldBoy!',
  'com.robert.DosBox': 'Magic DosBox',
  'com.fishstix.dosbox': 'DosBox Turbo',
  'com.eltechs.ed': 'ExaGear',
  'com.eltechs.es': 'ExaGear Strategies',
  'com.reicast.emulator': 'Reicast',
  'com.reicast.flycast': 'Flycast',
  'org.mupen64plusae.v3.fzurita': 'Mupen64Plus FZ',
  'paulscode.android.mupen64plus.free': 'Mupen64Plus AE Free',
  'com.duckstation.android': 'DuckStation',
  'com.bigpemu': 'BigPEmu',

  // Emulators - Nintendo
  'com.dsemu.drastic': 'DraStic',
  'me.magnum.melonds': 'melonDS',
  'org.citra.citra': 'Citra',
  'org.ryujinx': 'Ryujinx',
  'com.winlator.app': 'Winlator',

  // Emulators - Multi-System
  'com.explusalpha.NesEmu': 'NES Emulator',
  'com.explusalpha.Snes9xPlus': 'Snes9x EX+',
  'com.explusalpha.MdEmu': 'MD.emu',
  'com.explusalpha.GbaEmu': 'GBA.emu',
  'com.explusalpha.GbcEmu': 'GBC.emu',
  'com.bubble.emulator': 'Pizza Boy GBA',
  'com.bubble.gbcemulator': 'Pizza Boy GBC',

  // Frontend Launchers
  'com.bigpicture.mode': 'Daijisho',
  'com.fgl27.launcher': 'FGL Pro',
  'com.fgl27.enhancer': 'Game Enhancer',
  'tech.digdug.pegasus.android': 'Pegasus',
  'com.reset.reset': 'Reset Collection',

  // Browsers
  'org.mozilla.firefox': 'Firefox',
  'org.mozilla.firefox_beta': 'Firefox Beta',
  'org.mozilla.fenix': 'Firefox Fenix',
  'com.opera.browser': 'Opera',
  'com.opera.mini.native': 'Opera Mini',
  'com.opera.gx': 'Opera GX',
  'com.brave.browser': 'Brave Browser',
  'com.duckduckgo.mobile.android': 'DuckDuckGo',
  'com.microsoft.emmx': 'Microsoft Edge',
  'com.kiwibrowser.browser': 'Kiwi Browser',
  'com.UCMobile.intl': 'UC Browser',
  'com.sec.android.app.sbrowser': 'Samsung Internet',
  'com.vivaldi.browser': 'Vivaldi',
  'com.yandex.browser': 'Yandex Browser',

  // Finance & Banking
  'com.paypal.android.p2pmobile': 'PayPal',
  'com.venmo': 'Venmo',
  'com.squareup.cash': 'Cash App',
  'com.coinbase.android': 'Coinbase',
  'com.robinhood.android': 'Robinhood',
  'com.plaid.link': 'Plaid',
  'com.chime.android': 'Chime',
  'com.sofi.mobile': 'SoFi',
  'com.acorns.android': 'Acorns',
  'com.bankofamerica.mobile': 'Bank of America',
  'com.chase.sig.android': 'Chase Mobile',
  'com.wellsfargo.mobile.android': 'Wells Fargo',
  'com.usaa.mobile.android.usaa': 'USAA',
  'com.citi.citimobile': 'Citi Mobile',
  'com.revolut.revolut': 'Revolut',
  'com.binance.dev': 'Binance',
  'org.toshi': 'Coinbase Wallet',

  // Navigation & Travel
  'com.waze': 'Waze',
  'com.ubercab': 'Uber',
  'com.ubercab.eats': 'Uber Eats',
  'com.lyft.android': 'Lyft',
  'com.airbnb.android': 'Airbnb',
  'com.booking': 'Booking.com',
  'com.tripadvisor.tripadvisor': 'TripAdvisor',
  'com.expedia.bookings': 'Expedia',
  'com.hopper.mountainview.play': 'Hopper',
  'com.kayak.android': 'KAYAK',
  'com.skyscanner.android.main': 'Skyscanner',
  'com.grabtaxi.passenger': 'Grab',
  'com.ola.app': 'Ola',
  'com.bolt.android': 'Bolt',

  // Food Delivery
  'com.grubhub.android': 'Grubhub',
  'com.dd.doordash': 'DoorDash',
  'com.postmates.android': 'Postmates',
  'com.application.zomato': 'Zomato',
  'com.mcdonalds.app': 'McDonald\'s',
  'com.starbucks.mobilecard': 'Starbucks',
  'com.chipotle.ordering': 'Chipotle',
  'com.subway.mobile.subwayapp': 'Subway',

  // Utilities & Tools
  'com.adobe.reader': 'Adobe Acrobat',
  'com.adobe.lrmobile': 'Adobe Lightroom',
  'com.lastpass.lpandroid': 'LastPass',
  '1password.android': '1Password',
  'com.dashlane': 'Dashlane',
  'com.weather.Weather': 'Weather',
  'com.accuweather.android': 'AccuWeather',
  'com.wunderground.android.weather': 'Weather Underground',
  'com.shazam.android': 'Shazam',
  'com.truecaller': 'Truecaller',
  'com.microsoft.launcher': 'Microsoft Launcher',
  'com.teslacoilsw.launcher': 'Nova Launcher',
  'com.actionlauncher.playstore': 'Action Launcher',
  'ginlemon.flowerfree': 'Flower',
  'com.piriform.ccleaner': 'CCleaner',
  'com.avast.android.mobilesecurity': 'Avast Mobile Security',
  'com.avg.android.security.free': 'AVG AntiVirus',
  'com.cleanmaster.mguard': 'Clean Master',

  // Communication
  'com.skype.raider': 'Skype',
  'us.zoom.videomeetings': 'Zoom',
  'com.cisco.webex.meetings': 'Webex Meetings',
  'com.gotomeeting': 'GoToMeeting',
  'com.ringcentral.meetings': 'RingCentral Meetings',
  'com.skype.m2': 'Skype Lite',

  // Photo & Video Editing
  'com.vsco.cam': 'VSCO',
  'com.lightricks.facetune.free': 'Facetune',
  'com.neuralprisma': 'Prisma',
  'com.niksoftware.snapseed': 'Snapseed',
  'com.picsart.studio': 'PicsArt',
  'com.canva.editor': 'Canva',
  'com.adobe.spark.post': 'Adobe Spark Post',
  'com.camerasideas.instashot': 'InShot',
  'com.vimeo.android.videoapp': 'Vimeo',
  'com.nexstreaming.app.kinemasterfree': 'KineMaster',
  'com.cyberlink.powerdirector.DRA140225_01': 'PowerDirector',
  'videoeditor.videomaker.videoeditingapp': 'Video Editor',
  'com.prequel.app': 'Prequel',

  // Health & Fitness
  'com.fitbit.FitbitMobile': 'Fitbit',
  'com.myfitnesspal.android': 'MyFitnessPal',
  'com.nike.plusgps': 'Nike Run Club',
  'com.nike.ntc': 'Nike Training Club',
  'com.strava': 'Strava',
  'com.runtastic.android': 'Runtastic',
  'com.fitnesskeeper.runkeeper.pro': 'RunKeeper',
  'com.calm.android': 'Calm',
  'com.headspace.android': 'Headspace',
  'com.samsung.android.app.health': 'Samsung Health',
  'com.xiaomi.hm.health': 'Mi Fit',
  'com.huawei.health': 'Huawei Health',

  // News & Magazines
  'flipboard.app': 'Flipboard',
  'com.cnn.mobile.android.phone': 'CNN',
  'com.nytimes.android': 'The New York Times',
  'com.washingtonpost.android': 'The Washington Post',
  'com.bbc.news': 'BBC News',
  'com.guardian': 'The Guardian',
  'com.reuters.android': 'Reuters',
  'com.ap.mobile': 'AP News',
  'com.medium.reader': 'Medium',
  'com.feedly': 'Feedly',
  'com.smartnews.android': 'SmartNews',

  // Education & Reference
  'com.duolingo': 'Duolingo',
  'com.busuu.android': 'Busuu',
  'com.babbel.mobile.android.en': 'Babbel',
  'com.memrise.android.memrisecompanion': 'Memrise',
  'org.khanacademy.android': 'Khan Academy',
  'com.Coursera.android': 'Coursera',
  'com.udemy.android': 'Udemy',
  'com.google.android.apps.classroom': 'Google Classroom',
  'com.wolfram.android.alpha': 'Wolfram Alpha',
  'com.dictionary': 'Dictionary.com',
  'com.brainscape.apps.android': 'Brainscape',
  'com.quizlet.quizletandroid': 'Quizlet',

  // Dating
  'com.tinder': 'Tinder',
  'com.bumble.app': 'Bumble',
  'com.okcupid.okcupid': 'OkCupid',
  'net.match.android.matchmobile': 'Match',
  'com.hinge.app': 'Hinge',
  'com.pof.android': 'Plenty of Fish',
  'com.coffeemeetsbagel': 'Coffee Meets Bagel',
  'com.ourtime.android': 'OurTime',

  // System & Default Apps
  'com.android.settings': 'Settings',
  'com.android.camera2': 'Camera',
  'com.android.gallery3d': 'Gallery',
  'com.android.calculator2': 'Calculator',
  'com.android.calendar': 'Calendar',
  'com.android.deskclock': 'Clock',
  'com.android.contacts': 'Contacts',
  'com.android.dialer': 'Phone',
  'com.android.messaging': 'Messages',
  'com.android.music': 'Music',
  'com.android.email': 'Email',
  'com.android.fileexplorer': 'File Manager',
};
